### ISSUE TITLE
about - content font size

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-nicole-deltoro/geekwise-wordpress#8]
the font should not be bold, just the headers to each paragraph

**Comment by geekwise-nicole-deltoro** [comment]
done

**Comment by Sramos9191** [comment]
@geekwise-nicole-deltoro if you have already pushed please add "font-weight: 300;" to the p tag and if you have not pushed please do so ( I don't see the change in the content font size )

**Comment by geekwise-nicole-deltoro** [comment]
done

**Comment by Sramos9191** [comment]
I still don't see the change in the content font size: 

Please inspect the content portion on the geekwiseacademy.com/about page and adjust your code accordingly.

**Comment by geekwise-nicole-deltoro** [comment]
done
